### ISSUE TITLE
Error with script.

### ISSUE THREAD

**Issue by kashm07** [wimpywarlord/appliFLY#15]
/Users/kashyapmehta/PycharmProjects/Part-Time-Jobs/venv/bin/python /Users/kashyapmehta/PycharmProjects/Part-Time-Jobs/appliFly.py
Dᴇᴠᴇʟᴏᴘᴇᴅ Bʏ Kꜱʜɪᴛɪᴊ Dʜʏᴀɴɪ
@https://github.com/wimpywarlord

____________PRE-REQUISITES____________
1. Make sure have created a `.env` file in the same directory as this script.
2. Make sure have copied contents of the `env.txt` file into that `.env`.
3. Make sure have filled the `.env` file with your credentials and paths.
4. Make sure you installed all the dependencies: `pip install -r requirements.txt`
5. Make sure you have a good internet connection.
6. Make sure you have applied to atleast 1 job on the portal manually.

____________NOTES____________
1. You will need to 1 time authenticate using DUO. Make sure you have your phone with you.
2. If the script crashes for any reason. Simply Restart It. It will work the next time, give it a few tries.
3. In case of errror, document the error and report to the github repository @https://github.com/wimpywarlord/appliFLY/issues
4. If you have already applied for a job, the script will skip it.

An error occured. Please document & report it to the developer @https://github.com/wimpywarlord/appliFLY/issues
Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[3]/div[2]/main[3]/div/div/div/div[2]/div/div/div/div/div[1]/div/div/div/div[1]/a/button"}
  (Session info: chrome=120.0.6099.71); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
0   chromedriver                        0x000000010b575c48 chromedriver + 4852808
1   chromedriver                        0x000000010b56d1b3 chromedriver + 4817331
2   chromedriver                        0x000000010b1397bd chromedriver + 411581
3   chromedriver                        0x000000010b189e30 chromedriver + 740912
4   chromedriver                        0x000000010b189fe1 chromedriver + 741345
5   chromedriver                        0x000000010b1d5864 chromedriver + 1050724
6   chromedriver                        0x000000010b1b3c2d chromedriver + 912429
7   chromedriver                        0x000000010b1d2ae2 chromedriver + 1039074
8   chromedriver                        0x000000010b1b39a3 chromedriver + 911779
9   chromedriver                        0x000000010b17b103 chromedriver + 680195
10  chromedriver                        0x000000010b17c71e chromedriver + 685854
11  chromedriver                        0x000000010b535792 chromedriver + 4589458
12  chromedriver                        0x000000010b53a99c chromedriver + 4610460
13  chromedriver                        0x000000010b51acb1 chromedriver + 4480177
14  chromedriver                        0x000000010b53b716 chromedriver + 4613910
15  chromedriver                        0x000000010b50c23c chromedriver + 4420156
16  chromedriver                        0x000000010b55b798 chromedriver + 4745112
17  chromedriver                        0x000000010b55b94e chromedriver + 4745550
18  chromedriver                        0x000000010b56cdf3 chromedriver + 4816371
19  libsystem_pthread.dylib             0x00007ff8108cb202 _pthread_start + 99
20  libsystem_pthread.dylib             0x00007ff8108c6bab thread_start + 15

Process finished with exit code 0 
#9

**Comment by wimpywarlord** [comment]
Closing with FIX in [this](https://github.com/wimpywarlord/appliFLY/commit/400b7ae2b35214a3a4b0605279353734f703a0ff) commit.
