### ISSUE TITLE
Code runs fine. Doesn't apply to any jobs though. Shows below msg. Anything I can do to fix this?

### ISSUE THREAD

**Issue by BiprarshiD** [wimpywarlord/appliFLY#2]
All jobs staged for application.
____________JOB LINKS FOUND____________
There are 0 jobs available for you to apply.

It shows me the above message.

**Comment by jfs-rupesh** [comment]
I am also getting same output. Do we need to apply filter in by.py file?

**Comment by wimpywarlord** [comment]
Thankyou for bringing this to my notice, looking into this.

**Comment by wimpywarlord** [comment]
Developer Note:

The possible point of failure could be that the script is unable to detect the job-titles within the allotted time frame.

A possible fix for this could be awaiting the presence of the job titles elements on the DOM/ webpage before we extract all the links.

The following line of could should achieve that behaviour. I have created an PR, and added this to main. **_Redownload the script and try to run it._**

```
wait_for_job_title_links = WebDriverWait(chromeDriver, 10)
wait_for_job_title_links.until(EC.presence_of_element_located((By.CLASS_NAME, "jobtitle")))
job_title_links = chromeDriver.find_elements(By.CLASS_NAME, 'jobtitle')
```

If that does not solve the problem, I would recommend to start with playing around with these timers listed in the picture below.

![Screenshot at Sep 12 20-25-44](https://github.com/wimpywarlord/appliFLY/assets/41532804/428ff82c-ecf7-434a-99ef-be5bccbfb159)

Additionally, I would  recommend downloading the latest version of Google Chrome from here: https://www.google.com/chrome/

If that does not work, I would recommend, making sure you have a good internet connection and using a different machine and experiment with different networks.

If you need further assistance, I would need you to send a screen recording on your system with the console logs and the script behavior on the browser.

**Comment by hartik123** [comment]
Codin is running and is able to search for few jobs as well, and opens up 1 job but doesn't apply to it.

**Comment by wimpywarlord** [comment]
> Codin is running and is able to search for few jobs as well, and opens up 1 job but doesn't apply to it.

Please provide some more information for bug tracking.

Potential evidence:

Chrome version
Python version
Screen recording or screenshot of error or script behavior.
Script logs

**Comment by wimpywarlord** [comment]
Up

> Developer Note:
> 
> The possible point of failure could be that the script is unable to detect the job-titles within the allotted time frame.
> 
> A possible fix for this could be awaiting the presence of the job titles elements on the DOM/ webpage before we extract all the links.
> 
> The following line of could should achieve that behaviour. I have created an [PR](https://github.com/wimpywarlord/appliFLY/pull/4), and added this to main. **_Redownload the script and try to run it._**
> 
> ```
> wait_for_job_title_links = WebDriverWait(chromeDriver, 10)
> wait_for_job_title_links.until(EC.presence_of_element_located((By.CLASS_NAME, "jobtitle")))
> job_title_links = chromeDriver.find_elements(By.CLASS_NAME, 'jobtitle')
> ```
> 
> If that does not solve the problem, I would recommend to start with playing around with these timers listed in the picture below.
> 
> ![Screenshot at Sep 12 20-25-44](https://user-images.githubusercontent.com/41532804/267524779-428ff82c-ecf7-434a-99ef-be5bccbfb159.png)
> 
> Additionally, I would recommend downloading the latest version of Google Chrome from here: https://www.google.com/chrome/
> 
> If that does not work, I would recommend, making sure you have a good internet connection and using a different machine and experiment with different networks.
> 
> If you need further assistance, I would need you to send a screen recording on your system with the console logs and the script behavior on the browser.

Update

![WhatsApp Image 2023-09-12 at 23 03 56](https://github.com/wimpywarlord/appliFLY/assets/41532804/c6d82e1d-302c-4b19-8ec5-ae137c9b8fff)

Able to detect 10 jobs, but fails beyond that

**Comment by wimpywarlord** [comment]
> Up
> 
> > Developer Note:
> > The possible point of failure could be that the script is unable to detect the job-titles within the allotted time frame.
> > A possible fix for this could be awaiting the presence of the job titles elements on the DOM/ webpage before we extract all the links.
> > The following line of could should achieve that behaviour. I have created an [PR](https://github.com/wimpywarlord/appliFLY/pull/4), and added this to main. **_Redownload the script and try to run it._**
> > ```
> > wait_for_job_title_links = WebDriverWait(chromeDriver, 10)
> > wait_for_job_title_links.until(EC.presence_of_element_located((By.CLASS_NAME, "jobtitle")))
> > job_title_links = chromeDriver.find_elements(By.CLASS_NAME, 'jobtitle')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If that does not solve the problem, I would recommend to start with playing around with these timers listed in the picture below.
> > ![Screenshot at Sep 12 20-25-44](https://user-images.githubusercontent.com/41532804/267524779-428ff82c-ecf7-434a-99ef-be5bccbfb159.png)
> > Additionally, I would recommend downloading the latest version of Google Chrome from here: https://www.google.com/chrome/
> > If that does not work, I would recommend, making sure you have a good internet connection and using a different machine and experiment with different networks.
> > If you need further assistance, I would need you to send a screen recording on your system with the console logs and the script behavior on the browser.
> 
> Update
> 
> ![WhatsApp Image 2023-09-12 at 23 03 56](https://user-images.githubusercontent.com/41532804/267734803-c6d82e1d-302c-4b19-8ec5-ae137c9b8fff.jpeg)
> 
> Able to detect 10 jobs, but fails beyond that

Potenial Culprit: https://developer.apple.com/forums/thread/105810

**Comment by BiprarshiD** [comment]
Doesn't apply to any job. Downloaded updated script. Debug msgs below:

DevTools listening on ws://127.0.0.1:57066/devtools/browser/dd9b37d3-dfed-47b7-8a67-12786e588235
[17912:17216:0915/090307.508:ERROR:cert_issuer_source_aia.cc(36)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate

[17912:17216:0915/090307.875:ERROR:cert_issuer_source_aia.cc(36)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate

All jobs staged for application.
An error occured. Please document & report it to the developer @https://github.com/wimpywarlord/appliFLY/issues
Message:
Stacktrace:
        GetHandleVerifier [0x00007FF6555B7862+54818]
        (No symbol) [0x00007FF655526A92]
        (No symbol) [0x00007FF6553DDA3B]
        (No symbol) [0x00007FF65541E4FC]
        (No symbol) [0x00007FF65541E67C]
        (No symbol) [0x00007FF655459627]
        (No symbol) [0x00007FF65543EAEF]
        (No symbol) [0x00007FF6554575A2]
        (No symbol) [0x00007FF65543E883]
        (No symbol) [0x00007FF655413691]
        (No symbol) [0x00007FF6554148D4]
        GetHandleVerifier [0x00007FF65591B962+3610402]
        GetHandleVerifier [0x00007FF655971830+3962352]
        GetHandleVerifier [0x00007FF655969D1F+3930847]
        GetHandleVerifier [0x00007FF655653616+693206]
        (No symbol) [0x00007FF6555315F8]
        (No symbol) [0x00007FF65552D904]
        (No symbol) [0x00007FF65552DA32]
        (No symbol) [0x00007FF65551E0E3]
        BaseThreadInitThunk [0x00007FFED258257D+29]
        RtlUserThreadStart [0x00007FFED316AA68+40]

**Comment by wimpywarlord** [comment]
> ERROR: Couldn't read tbsCertificate as SEQUENCE
> ERROR: Failed parsing Certificate

@BiprarshiD possible resolution https://stackoverflow.com/questions/75160044/how-to-resolve-this-error-in-selenium-error-couldnt-read-tbscertificate-as-s

I am working on dockerizing the app, so as to bypass system specific errors

**Comment by wimpywarlord** [comment]
### Solution

This turned out to versioning issue, between selenium driver, python and chrome.

I found an error in the script logs saying:

`ERROR:page_load_metrics_update_dispatcher.cc(194)] Invalid first_paint error using Selenium Python ChromeDriver`

Upon surfing the web, I found this thread: https://stackoverflow.com/questions/75830184/errorpage-load-metrics-update-dispatcher-cc194-invalid-first-paint-error-usi

It talks about how the above error message indicates that there is a mismatch between the binary versions you are using.

On a more deeper level

As per the [[comment](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3341#c1)](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3341#c1) within the [[discussion](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3341)](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3341):

> The supported configuration is to always match the version between Chrome and ChromeDriver - so when you are using Chrome 80, you should use Chrome 80. It is also possible to run ChromeDriver N with Chrome N+1, but this will always generate the warning you see. Most operations will complete successfully, but it is not the recommended approach.
> 
> 
> The solution is to upgrade ChromeDriver to version 80: https://chromedriver.chromium.org/downloads
> 

This is understandable because, most of the operations were working fine in the script, but some operations were acting wonky.

***The straight and simple solution is to***

You need to ensure:

- **ChromeDriver** is updated to the latest version - as of 21st October 2023 - that is 118.0.XXXX.X family

Go to Google’s official driver support website: https://chromedriver.chromium.org/downloads and then go to the downloads section : https://googlechromelabs.github.io/chrome-for-testing/

Download the latest stable version of the chrome driver according to your operating system : https://googlechromelabs.github.io/chrome-for-testing/#stable

Copy the absolute path to the `chrome.exe` file inside the downloaded chrome driver folder.
    
    
    Look into line number 61 in [appliFly.py](http://appliFly.py) file and uncomment as well as update the absolute path to the chrome driver which you just downloaded from the above mentioned link.
    
    ```
    # You can use other drivers like Firefox, Edge, etc.
    
      # ____________ If Facing Jobs 0 Jobs found issue ________________
      # Absolute Path to Chrome Driver Example: C:\Users\ASUS\Downloads\chrome\chrome.exe
      # chromeDriver = webdriver.Chrome(executable_path=r"Absolute Path to the Chrome Driver")  # Uncomment this if facing 0 jobs found issue
      # ____________ No Erros ____________________
      chromeDriver = webdriver.Chrome()  # Comment this out if facing 0 jobs found issue
    ```
    

- **Chrome Browser** is updated to the latest version - as of 21st October 2023 - that is the 118.0.XXX.X family 

Download the latest version chrome or update the existing version to the latest version. Here is how: https://support.google.com/chrome/answer/95414?hl=en&co=GENIE.Platform%3DDesktop

- **Selenium** is upgraded to current released ***[[Version 4.8.0](https://www.selenium.dev/downloads/)](https://www.selenium.dev/downloads/)***.
I have updated the requirements.txt file to include selenium `selenium==4.14.0` instead of `selenium==4.12.0`

Therefore re-clone the repository from Github and do a fresh `pip install -r requirements.txt`

**Comment by wimpywarlord** [comment]
Hey, @BiprarshiD I would be more than happy to assist you with this over a call if you are unable to figure it out.

Shoot any questions that you may have.

**Comment by wimpywarlord** [comment]
Closing, as resolved
